CREATE DATABASE FOOD_OASIS;
USE FOOD_OASIS;

CREATE TABLE BUYERS (
	BID INT NOT NULL AUTO_INCREMENT,
	EMAIL VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(16) NOT NULL,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (BID)
);

CREATE TABLE SELLERS (
	SID INT NOT NULL AUTO_INCREMENT,
	EMAIL VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	SELLER_NAME VARCHAR(255) NOT NULL,
	PHONE_NUMBER INTEGER(10) NOT NULL,
	STREET_ADDRESS VARCHAR(255) NOT NULL,
	PRIMARY KEY (SID)
);

CREATE TABLE PRODUCTS (
	PID INT AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	QUANTITY INT NOT NULL,
	PRICE DECIMAL(4, 2) NOT NULL,
	SID INT,
	PRIMARY KEY (PID),
	FOREIGN KEY (SID) REFERENCES SELLERS (SID)
);

CREATE TABLE CARTS (
	CID INT AUTO_INCREMENT,
	BID INT,
	SID INT,
	DATE_CREATED DATETIME NOT NULL,
	APPROVED BIT NOT NULL DEFAULT 0,
	PRIMARY KEY (CID),
	FOREIGN KEY (BID) REFERENCES BUYERS (BID),
	FOREIGN KEY (SID) REFERENCES SELLERS (SID)
);

CREATE TABLE CART_ITEMS (
    IID INT NOT NULL,
    CID INT,
    PID INT,
    QUANTITY INT NOT NULL,
    PRICE DECIMAL(4, 2) NOT NULL,
	PRIMARY KEY (IID),
	FOREIGN KEY (CID) REFERENCES CARTS (CID),
	FOREIGN KEY (PID) REFERENCES PRODUCTS (PID)
);